apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: react-flight-tracker-prod-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: react-flight-tracker-image
  policy:
    semver:
      range: x.x.x