apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../image-repository.yaml
commonLabels:
  env: prod
namespace: react-flight-tracker
namePrefix: prod-

images:
  - name: ghcr.io/apoorva64/react-flight-tracker
    newTag: master

patches:
  - target:
      kind: Ingress
      name: react-flight-tracker-ingress
    path: ingress-patch.yaml