apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  env: prod
namespace: react-flight-tracker
namePrefix: prod-

images:
  - name: ghcr.io/apoorva64/react-flight-tracker
    newTag: 1.0.0 # {"$imagepolicy": "flux-system:react-flight-tracker-prod-policy:tag"}

patches:
  - target:
      kind: Ingress
      name: react-flight-tracker-ingress
    path: ingress-patch.yaml
  - target:
      kind: ImagePolicy
      name: react-flight-tracker-policy
    path: image-policy-patch.yaml
  - target:
      kind: ImageUpdateAutomation
      name: react-flight-tracker-automation
    path: image-automation-patch.yaml